/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thema.graphab.addpatch;

import org.thema.graphab.graph.GraphGenerator;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.io.File;
import java.util.*;
import java.util.concurrent.CancellationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.thema.common.Config;
import org.thema.common.parallel.ProgressBar;
import org.thema.common.parallel.TaskMonitor;
import org.thema.drawshape.feature.DefaultFeature;
import org.thema.drawshape.layer.DefaultGroupLayer;
import org.thema.drawshape.layer.FeatureLayer;
import org.thema.graphab.MainFrame;
import org.thema.graphab.Project;
import org.thema.graphab.metric.global.GlobalMetric;

/**
 *
 * @author gvuidel
 */
public class AddPatchResultDialog extends javax.swing.JDialog {

    MainFrame mainFrame;
    DefaultGroupLayer layers;
    /**
     * Creates new form AddPatchResultDialog
     * @param parent
     */
    public AddPatchResultDialog(MainFrame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        mainFrame = parent;
        
        layers = new DefaultGroupLayer("Results");
        layers.addLayerFirst(new FeatureLayer("Patches", Project.getProject().getPatches()));
        mapViewer1.setRootLayer(layers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        mapViewer1 = new org.thema.drawshape.ui.MapViewer();
        graphPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add patches");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setLeftComponent(mapViewer1);

        graphPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(graphPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(closeButton)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(false);
                dispose();
                mainFrame.reloadProject();
            }
        });
        
    }//GEN-LAST:event_closeButtonActionPerformed

    public void addPatches(final int nbPatch, final File pointFile, final String capaField, final GlobalMetric indice, final GraphGenerator gen) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                ProgressBar bar = Config.getProgressBar();
                bar.setNote("Add patches...");
                try {
                    AddPatchCommand addPatchCmd = new AddPatchCommand(nbPatch, indice, gen, pointFile, capaField);
                    addPatchCmd.run(bar);
                    addPatchCmd.saveResults();
                    showResults(indice, gen, addPatchCmd.getAddedPatches(), addPatchCmd.getMetricValues());
                } catch(CancellationException cancel) {
                    closeButtonActionPerformed(null);
                } catch(Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(AddPatchResultDialog.this, ex);
                    closeButtonActionPerformed(null);
                } finally {
                    bar.close();
                }
            }
        }).start();
        
        setVisible(true);
    }
   
    public void addPatches(final int nbPatch, final double res, final File capaFile, final GlobalMetric indice, final GraphGenerator gen,
            final int nbMultiPatch, final int windowMulti) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                ProgressBar bar = Config.getProgressBar();
                bar.setNote("Add patches...");
                TaskMonitor mon = new TaskMonitor(AddPatchResultDialog.this, "Add patches", "", 0, 100);
                try {
                    AddPatchCommand addPatchCmd = new AddPatchCommand(nbPatch, indice, gen, capaFile, res, nbMultiPatch, windowMulti);
                    addPatchCmd.run(bar);
                    addPatchCmd.saveResults();
                    showResults(indice, gen, addPatchCmd.getAddedPatches(), addPatchCmd.getMetricValues());
                } catch(CancellationException cancel) {
                    closeButtonActionPerformed(null);
                } catch(Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(AddPatchResultDialog.this, ex);
                    closeButtonActionPerformed(null);
                } finally {
                    mon.close();
                }

            }
        }).start();
        
        setVisible(true);
    }
    
    private void showResults(GlobalMetric indice, GraphGenerator gen, List<DefaultFeature> addedPatches, TreeMap<Integer, Double> indiceValues) {
        XYSeries serie = new XYSeries("Serie");
        for(Integer nbPatch : indiceValues.keySet())
            serie.add(nbPatch, indiceValues.get(nbPatch));
        JFreeChart chart = ChartFactory.createXYLineChart(null, "# added patch", indice.getDetailName(), 
                new XYSeriesCollection(serie), PlotOrientation.VERTICAL, false, false, false);
        ((NumberAxis)chart.getXYPlot().getRangeAxis()).setAutoRangeIncludesZero(false);
        ChartPanel chartPanel = new ChartPanel(chart);
        graphPanel.add(chartPanel, BorderLayout.CENTER);

        layers.addLayerFirst(new FeatureLayer("Patches added", addedPatches));
        layers.addLayerLast(new GraphGenerator(gen, "").getLayers());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private org.thema.drawshape.ui.MapViewer mapViewer1;
    // End of variables declaration//GEN-END:variables
}
