
package org.thema.graphab.metric;

import java.awt.BorderLayout;
import java.util.Map;
import org.thema.common.param.DefaultParamEditor;

/**
 * Default ParamPanel for metric parameters editing.
 * Use {@link DefaultParamEditor}
 * 
 * @author Gilles Vuidel
 */
public class DefaultParamPanel extends ParamPanel {
    
    private Metric metric;
    
    /**
     * Creates new form DefaultParamPanel
     * @param metric the metric to edit parameters
     */
    public DefaultParamPanel(Metric metric) {
        initComponents();
        this.metric = metric;
        DefaultParamEditor editor = new DefaultParamEditor(metric);
        panel.add(editor, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map<String, Object> getParams() {
        return metric.getParams();
    }
}
